include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-xBZc

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: onb-br-enum-gender-fn-4f7fbd04-5c9d-46c1-b17c-799fda7a256b
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-xBZc
  environment:
    name: onb-br-enum-gender-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-05T15:17:16Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: onb-br-enum-gender-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      SpecializationTimeout: 120
    StrategyType: execution
  concurrency: 500
  environment:
    name: onb-br-enum-gender-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: onb-br-enum-gender-fn-4f7fbd04-5c9d-46c1-b17c-799fda7a256b
      namespace: default
  requestsPerPod: 10000
  resources:
    requests:
      cpu: 128m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi
