include:
- ./func/*
kind: ArchiveUploadSpec
name: func-voxv

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fn-get-gender-7fc19700-2f4a-42ca-ad33-2b26bfdf7a4d
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: env-get-gender
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-voxv
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-26T16:29:06Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fn-get-gender
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: env-get-gender
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_enums
    packageref:
      name: fn-get-gender-7fc19700-2f4a-42ca-ad33-2b26bfdf7a4d
      namespace: default
  requestsPerPod: 1
  resources: {}
