apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: ae1f7e6b-ba19-4aa7-83de-7ead2a84d96f
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-gender
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/gender
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/gender
