include:
- ./func/*
kind: ArchiveUploadSpec
name: func-HLFs

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fn-get-gender-c7bb911e-0f7c-479d-b8d7-4478037de104
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: env-get-gender
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-HLFs
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-24T10:46:40Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fn-get-gender
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: env-get-gender
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_enums
    packageref:
      name: fn-get-gender-c7bb911e-0f7c-479d-b8d7-4478037de104
      namespace: default
  requestsPerPod: 1
  resources: {}
