apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 6686bbc7-1465-4189-957c-09c597195517
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-gender
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/gender
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/gender
